---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-config
  namespace: default
data:
  logstash-config-file: |
    input {
      beats {
        port => 5000
        }
    }
    
    filter {
      #  grok {
      #  match => ["message", "(?<timestamp>%{MONTHDAY}-%{MONTH}-%{YEAR} %{TIME}) queries: client %{IPV4:c_ip}#%{NUMBER:c_port}: query: %{NOTSPACE:queryrec} %{NOTSPACE:dnsclass} %{NOTSPACE:dnstype} \+ \(%{IPV4:dnsbind}\)"]
      #}
    }
    output {
      #stdout { codec => rubydebug }
      elasticsearch {
        hosts => ["elasticsearch-client:9200"]
        index => "logstash-k8s-%{+YYYY.MM.dd}"
      }
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: logstash
  namespace: default
  labels:
    component: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      component: logstash
  template:
    metadata:
      labels:
        component: logstash
    spec:
      containers:
      - name: logstash
        #        image: dockerhub-pr.yeshj.com/ops/logstash:7.2.0
        image: docker.io/baiyuliu/logstash
        command: ["/bin/sh","-c"]
        args: ["/usr/share/logstash/bin/logstash -f /usr/share/logstash/config/logstash.conf"]
        volumeMounts:
        - name: vm-config
          mountPath: /usr/share/logstash/config
      imagePullSecrets:
      - name: regcred-elastic
      volumes:
      - name: vm-config
        configMap:
          name: logstash-config
          items:
          - key: logstash-config-file
            path: logstash.conf
