apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    component: logstash
spec:
  type: NodePort
  selector:
    component: logstash
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30005
